### ISSUE TITLE
IT_06: refactor ELK

### ISSUE THREAD

**Issue by UnceptionAtlas** [UnceptionAtlas/supervision-docker-deploy#5]

**Comment by mhafidi** [comment]
refactor done with [UnceptionAtlas](https://github.com/UnceptionAtlas) merged commit [72015b9](https://github.com/UnceptionAtlas/supervision-docker-deploy/commit/72015b95ee5d90f5c3f78f4b4df0022681601c02) into main [now](https://github.com/UnceptionAtlas/supervision-docker-deploy/pull/6#event-13865236814)
